language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
  - clang -coverage -O0 Test.php -o 2
  - ./Test
  - gcov Test.php

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://coveralls.io/bash)




